apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: almoxarifado
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: almoxarifado
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - gateway:8080
              - server:8888
              - items:8081
              - servicos:8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: almoxarifado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.5.0
          args:
            - --config.file=/etc/prometheus/prometheus.yml
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: almoxarifado
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http