spring.application.name=almoxarifado_server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/brunowbbs2/config-server.git

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
